language: java

jdk:
- oraclejdk8

notifications:
  email:
    - fede.el.xeneize@gmail.com
    - fede.el.xeneize@hotmail.com
  on_success: always
  on_failure: always

cache:
  directories:
  - $HOME/.m2